main: com.minegusta.donatorpoints.DonatorPointsPlugin
author: janie177
version: ${project.version}
name: DonatorPoints
softdepend: [CensoredLib, WorldEdit, WorldGuard]
commands:
  points:
    usage: /Points
    permission: minegusta.donator
  npc:
    usage: /NPC Name
  horse:
    usage: /Horse
permissions:
  minegusta.donator:
    default: op