main: com.minegusta.minegustarpg.MinegustaRPGPlugin
author: janie177
version: ${project.version}
name: MinegustaRPG
softdepend: [CensoredLib, WorldEdit, WorldGuard]
commands:
  points:
    usage: /Points
  npc:
    usage: /NPC Name
  horse:
    usage: /Horse
  level:
    usage: /Level
    aliases: [l, rpg, lv, lvl, exp, experience]